apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-kafka

resources:
  - ./../../base/kafka
  - ./../../base/grafana
  - ./../../base/influxDB
  - ./../../base/telegraf
  - ./../../base/producers
  - ingress.yaml

secretGenerator:
  - name: my-secret
    literals:
      - username=admin
      - password=secretpassword

configMapGenerator:
  - name: telegraf-conf
    files:
      - telegraf.conf
  - name: telegraf-config
    literals:
      - INFLUXDB_URL=http://influxdb-service:8086
  - name: zookeeper-config
    literals:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  - name: kafka-config
    literals:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CREATE_TOPICS=garden_sensor_data:1:3
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  - name: influxdb-config
    literals:
      - INFLUXDB_HOST=influxdb-service
      - INFLUXDB_PORT=8086
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=dontusemepassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org 
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
