apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
        - name: kafka2
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka2:9092"
          envFrom:
          - configMapRef:
              name: kafka-config
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: kafka2-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka2-data
          persistentVolumeClaim:
            claimName: kafka2-pvc